### ISSUE TITLE
Missing `dotenv` dependency?

### ISSUE THREAD

**Issue by kevincon** [zackurben/alphavantage#10]
Hey, thanks for creating this module. :) It works great for my purposes, but when I first installed it via `npm install alphavantage` I couldn't `require('alphavantage')` until I also manually ran `npm install dotenv`. I think because your `package.json` file uses `index.js` as `main` and `index.js` requires `dotenv`, shouldn't `dotenv` be in `dependencies` in `package.json` instead of `devDependencies`?

**Comment by zackurben** [comment]
@kevincon thanks for the notice, it started as a dev dependency than snuck into the primary codebase lol

This will be fixed when https://github.com/zackurben/alphavantage/pull/11 is merged and `0.0.7` is published. Cheers 👍
