### ISSUE TITLE
Question on how to get stock realtime data

### ISSUE THREAD

**Issue by goxr3plus** [zackurben/alphavantage#110]
First off all :) 
Very interesting library i am using it for my new website . 
Thank you soooooooo much for creating it. 

I don't know how to get for example the latest price for example of NIO stock

const nioPrice = await alpha.data.intraday(`nio`);

for example this returns me a big object with intraday prices , i just need the latest ...

@zackurben

**Comment by goxr3plus** [comment]
I see alphavantage has partnered with https://polygon.io/stocks for that reason ?

**Comment by zackurben** [comment]
@goxr3plus I think you are correct. I don't (haven't ever) worked for AV so your guess is as good as mine.

Cheers
