### ISSUE TITLE
Can you please add support for the new TIME_SERIES_INTRADAY_EXTENDED

### ISSUE THREAD

**Issue by funnel20** [zackurben/alphavantage#274]
Recently AlphaVantage has added a new API function `TIME_SERIES_INTRADAY_EXTENDED`, see: https://www.alphavantage.co/documentation/#intraday-extended 

Can you please add this?

It would be preferred to have the optional parameter `adjusted` in as well. Also for `TIME_SERIES_INTRADAY`, which is currently lacking in `alpha.data.intraday(symbol, outputsize, datatype, interval)`

Thank you in advance.

**Comment by zackurben** [comment]
Sorry for the delay, my notifications got turned off for github.... I just added support for this in `alphavantage@2.4.1`

For future reference any new endpoint can be used with the `.experimental` api:

```
// example if not supported already
alpha.experimental('SOME_AV_ENDPOINT', { symbol: 'XYZ', param2: 'abc'});
```

**Comment by funnel20** [comment]
Hi Zack, this is awesome, thank you for adding this and teaching me about the `experimental()` function.
Can you please tag/release this new version 2.4.1 on GitHub, as it's not shown yet at https://github.com/zackurben/alphavantage/releases

Thank you.

**Comment by zackurben** [comment]
@funnel20 done: https://github.com/zackurben/alphavantage/releases/tag/2.4.1

Sorry, GH actions are on my roadmap to help prevent these human errors lol 😅
