### ISSUE TITLE
Is there a problem with the build? I see there is a build error.

### ISSUE THREAD

**Issue by FlexionCodeReview** [zackurben/alphavantage#36]
Is there a problem with the build? I see there is a build error.

**Comment by zackurben** [comment]
@FlexionCodeReview the last build before release 1.1.0 [passed](https://travis-ci.org/zackurben/alphavantage/builds/323875801), but travis seems to be having some issues this week. Everything is good to use now, but it may take a bit to fix the build status! Thanks
