### ISSUE TITLE
fetching error

### ISSUE THREAD

**Issue by Gahoul** [zackurben/alphavantage#368]
Hi, @zackurben   @IanMitchell  @jzatt
 it might be me but i cant seem to make this work...
When i call :
<script>alpha.crypto.daily('btc', 'usd').then((data) => {
console.log(data);
 });
</script>
I get error:
bundle.js:324 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
    at bundle.js:324:32
    at Object.daily (bundle.js:371:18)
    at (index):522:59
(anonymous) @ bundle.js:324
(anonymous) @ bundle.js:371
(anonymous) @ (index):522
Promise.then (async)
(anonymous) @ (index):522

I cant seem to figure it out, help please

**Comment by zackurben** [comment]
Hi @Gahoul, it looks like you are missing your api key:

```
const alpha = alphavantage({ key: 'qweqweqwe' });
alpha.crypto.daily('btc', 'usd').then((data) => { console.log(data); });
```
