### ISSUE TITLE
Real time data - subscribe

### ISSUE THREAD

**Issue by aarontanzk** [zackurben/alphavantage#63]
Hi, if I'm looking to get real-time data on specific time intervals like 1 min, does this package take care of the subscription to the API or I will have to implement ?

**Comment by zackurben** [comment]
@aarontanzk This package does not handle that, just the API communication. You will need to set up a mechanism to pull on an interval, e.g. [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout)

```js
setTimeout(<API call>, 60 * 1000);
```
