### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jdubz93** [zackurben/alphavantage#70]
node_modules/alphavantage/index.js:3
import Util from './lib/util';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by zackurben** [comment]
Hi @jdubz93, how are you trying to use this? It seems like you aren't using a bundler so [these directions may be useful to you](https://github.com/zackurben/alphavantage#browser-usage)

**Comment by rogerkerse** [comment]
exactly the same error when using it in node environment with

import api from 'alphavantage'

**Comment by aDevCalledAlex** [comment]
I am having the same issue. I am very confused because I thought that node could only use require instead of import and module.exports instead of export.

I am fairly new to node but this has never happened in any other node module I've used. Am I missing something here?

**Comment by zackurben** [comment]
Alright, it seems like you all stumbled upon the same error.

>I am having the same issue. I am very confused because I thought that node could only use require instead of import and module.exports instead of export.

You are correct, however, with babel (a transpiler) you can. The reason you would use it, is to modernize/standardize/augment your environment. It seems like I've broken the node build while adding browser support 🤦‍♂ 

You can install the previous version (without browser support) with:

```bash
npm i alphavantage@1.2.6
```

This should fix your issues, until I can push out the next build! Sorry all!

**Comment by tech2serve** [comment]
So what is the intent with "browser support"?

**Comment by zackurben** [comment]
Hi all, thanks for your interest in this bug. As of now, it has been closed 🎉

Please use the latest version `2.0.1` for all your browser and node.js needs. Sorry for the delay.
