### ISSUE TITLE
Wrapper for Fundamental Data

### ISSUE THREAD

**Issue by dillonco** [zackurben/alphavantage#87]
Part of the AlphaVantage documentation mentions some endpoints that give generic company information, I was wondering if the wrapper for these endpoints exist?

Specifically the `Company Overview`, example: https://www.alphavantage.co/query?function=OVERVIEW&symbol=IBM&apikey=demo

**Comment by zackurben** [comment]
This is now available in `2.2.0`, thanks to @akerra6993 🎉
