### ISSUE TITLE
Does AlphaVantage or this package support a custom date range?

### ISSUE THREAD

**Issue by alittletf** [zackurben/alphavantage#90]
Been looking at the docs and this package to find the ability to send a startDate & endDate type of params but no api seems to support it? how would you go about specific 90 day range in 2016? 

Thanks in advance!

**Comment by zackurben** [comment]
Hey @alittletf - sorry for the delay! The API doesn't appear to support dates for most of the endpoints. I'm not actually associated with the company but I'm sure they'd love to hear your suggestion through the support email. They have been very responsive with me in the past.
